version: '3'
services:
   db:
      restart: always
      image: postgres:12.9
      container_name: db
      environment:
         
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_DATABASE}
      volumes:
         - ./db/thrymr:/var/lib/postgresql/data
      ports:
         - 5432:5432
         
   ctrl:
      container_name: ctrl
      build: ./ctrl
      
      ports:
         - 3006:3006
      
      volumes:
         - /dev:/dev
         - /run/udev:/run/udev:ro
         - ./ctrl:/usr/src/ctrl
         - /usr/src/ctrl/node_modules
      privileged: true
      entrypoint: ["npm", "start"]

   api:
      restart: always
      container_name: api
      build: ./api
      command: cp .env /api/
      environment:
         PYTHONUNBUFFERED: 1
      volumes:
         - ./api:/app
      ports:
         - 5000:5000
      entrypoint: ["python3", "main.py"]

   client:
      container_name: client
      build: ./client
      ports:
         - 3000:3000
      volumes:
         - ./client:/usr/src/app
         - /usr/src/app/node_modules
      entrypoint: ["npm", "start"]

